# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/mxab/trivy
    rev: eb31ef229cbd1ed76b7e2becc6bec0614240e389
    hooks:
    -   id: trivyfsall
        args:
            - --skip-files=.git
    -   id: trivyfs
        args:
            - .
