# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/mxab/trivy
    rev: 4bc64b8ed615e366a18f7aa4c59ce96ddfb541c4
    hooks:
    -   id: trivyfs
        args:
            - .
