# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/mxab/pre-commit-trivy
    rev: 3add6e3bc025c7083b52eed7d106d3441f7afbee
    hooks:
    -   id: trivyfs-docker
        args:
            - .
