# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/mxab/pre-commit-trivy
    rev: v0.1.0
    hooks:
    -   id: trivyfs-docker
        args:
            - .
