# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: ../pre-commit-trivy
    rev: 0d0de8bd1506627e3ad8387831f8b10979da3344
    hooks:
    -   id: trivyfs-docker
        args:
            - .
