# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/mxab/trivy
    rev: ec60db3eca5500981a40f955422c7c12d5d37cd9
    hooks:
    -   id: trivyfs-docker
        args:
            - .
